GSR: Fix scale values, and handle sort fields with SQL expression
koordinates/geoserver pull request #19
Opened 2024-08-12 10:01 UTC by skim618

This PR contains two main fixes:

- For Coordinate Systems with metre unit: it's required to be a double but it's currently performing an Integer operation. Returning `1e-9` for radians so return the equivalent of (1/10000) = `1e-4`
- Handle basic string expressions in `orderByFields` parameter
    - Sorting (string) fields in ArcPRO does a request with an `UPPER()` function in the  `orderByFields` parameter. eg. `orderByFields=UPPER(field)`
 
`orderByFields` is case-insensitive anyways, so there's not much point evaluating these expressions.
Furthermore, it doesn't support all string expressions (eg. `CONCAT`, `SUBSTRING`)...
So ignore the string expressions as of now.

2024-08-14 20:01 UTC, hamishcampbell approved these changes

2024-08-14 20:12 UTC, hamishcampbell requested changes

2024-08-14 20:12 UTC, hamishcampbell commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
> +                }
Actually, is the expression ignored?

2024-08-14 20:13 UTC, hamishcampbell commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
> +                }
`a, B, c, D` would sorted differently if `UPPER` is applied, so if we're just dropping this we'll get some unexpected results?

2024-08-14 20:17 UTC, hamishcampbell commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
> +                }
Ah

> orderByFields is case-insensitive anyways, so there's not much point evaluating these expressions.
Furthermore, it doesn't support all string expressions (eg. CONCAT, SUBSTRING)...
So ignore the string expressions as of now.

Ok - any idea what it would take to support it?

2024-08-14 21:37 UTC, skim618 commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
> +                }
Unsure, but might be complex - I'm letting the `SortBy` class handle ordering, and I don't think they provide the option to allow more complex sorting - such as the sort options below.

It seems like ESRI supports three kinds of sorting, 
- `UPPER()`, `LOWER()`, and `CHAR_LENGTH()` (which is the number of characters in the field)

2024-08-16 01:37 UTC, hamishcampbell approved these changes

2024-08-16 02:35 UTC, merged