GSR: Add FeatureCount Model to enable `returnCountOnly` feature query
koordinates/geoserver pull request #2
Opened 2024-04-30 01:21 UTC by skim618

This PR also has some other minor improvements, such as:
- Removing the feature ID from the feature object (It is already inside `feature.attributes`)
- Keeping the objectid alias consistent with the field name
- Set the name of the feature layer to its title

### References
SC Ticket: [SC-13076](https://app.shortcut.com/koordinates/story/13076/solve-geoserver-gsr-issues-loading-data-into-arcpro)

Related Slack Thread that show the result of this change: https://koordinates.slack.com/archives/C06P77TQRK4/p1712638905212539

### Checklist

- [x] I've reviewed the diff myself
- [x] Note any new dependencies, link to discussion and approval status
- [x] Tests have been updated

### Why you made these changes?
With our current PoC we're able to _attempt_ to load data into ArcPro, however the actual geometry/attribute data isn't loaded. ArcPro correctly zooms to the right area, and the attribute table has the right column names, but the data itself doesn't load.

Debugging with Charles Proxy; ArcPRO was making a query request with `returnCountOnly=true`. However, this parameter wasn't enabled for GSR. It was expecting a response with `"count": 123` but was returning a normal `/query` response. 

It was confirmed that it was making this request with KoopJS as well, but Koop's endpoint was showing the correct number of feature counts. 

### How have you solved the problem?
Added the `returnCountOnly` query parameter to the query endpoint. 

### Risks involved
There shouldn't be any.

#### Are there possible or actual performance implications for this change?
Possibly when iterating through large number of features?

### Deployment/Migration

2024-04-30 02:42 UTC, hamishcampbell approved these changes
Note copyright notice, otherwise good.

2024-04-30 02:42 UTC, hamishcampbell commented on src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureCount.java
> + */
dorp this? This is our code so if anything (c) to us.

2024-04-30 18:51 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureCount.java
> + */
```
/* Copyright (c) 2024 Koordinates Limited. All rights reserved.
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */

2024-04-30 18:55 UTC, rcoup reviewed
I'm surprised more tests don't need updating?

2024-04-30 18:55 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/model/map/AbstractLayerOrTable.java
> +        this.name = layer.getTitle();
Is the cause of this that we're configuring the name incorrectly via the REST API? (is there an ID vs name vs title?)

2024-04-30 18:55 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
> +                    boolean returnCountOnly,
can we have a test for this?

2024-04-30 21:04 UTC, skim618 commented on src/community/gsr/src/main/java/org/geoserver/gsr/model/map/AbstractLayerOrTable.java
> +        this.name = layer.getTitle();
![Screenshot 2024-05-01 at 9 01 04 AM](https://github.com/koordinates/geoserver/assets/68880367/d0652155-5d59-4e63-b9df-0e9b1ea93961)

If done by `getName()`, the title would be **layer-7467**, and loading this into ArcPRO will load layer-7467 in the legend as well.

2024-04-30 22:08 UTC, skim618 commented on src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
> +                    boolean returnCountOnly,
Yeap - added.

2024-05-01 21:15 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/model/map/AbstractLayerOrTable.java
> +        this.name = layer.getTitle();
I had a look and we set `FeatureType.name == FeatureType.nativeName`, and `FeatureType.title`. `.nativeName` is designed for a filename/table-name/etc, `.name` is the published identifier. So I think we're doing it right if we're just looking at FeatureTypes.

GeoServer has a "Layer" concept as well which could have it's own name, but IIUC we don't really use it.

2024-05-01 21:20 UTC, rcoup requested changes

2024-05-01 21:20 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
> +        try (FeatureIterator<F> iterator = features.features()) {
FeatureCollection has a `.size()` method... would that work?

https://docs.geotools.org/latest/userguide/library/main/collection.html#id1

2024-05-01 21:20 UTC, rcoup commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
> +        try (FeatureIterator<F> iterator = features.features()) {
If not, we don't appear to close the iterator?

> Please note that you should not treat a FeatureCollection as a normal in-memory Java collection - these are heavyweight objects and we must ask you to close any iterators you open.:

2024-05-01 21:55 UTC, skim618 commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
> +        try (FeatureIterator<F> iterator = features.features()) {
> https://docs.geotools.org/latest/userguide/library/main/collection.html#id1

Ah yes, will use `.size()`

2024-05-01 22:51 UTC, skim618 commented on src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
> +        try (FeatureIterator<F> iterator = features.features()) {
Tests pass and `returnCountOnly` works fine locally using `.size()`. Pretty big performance win as well

2024-05-01 22:56 UTC, rcoup approved these changes
👍

2024-05-03 03:16 UTC, merged