GSR: Enable POST to feature layer query endpoint
koordinates/geoserver pull request #5
Opened 2024-04-30 02:34 UTC by skim618

### References
https://koordinates.slack.com/archives/C06P77TQRK4/p1713329797886639?thread_ts=1713329464.637509&cid=C06P77TQRK4

### Checklist

- [x] I've reviewed the diff myself
- [x] Note any new dependencies, link to discussion and approval status
- [x] Tests have been updated

### Why you made these changes?
Big layers with LOTs of feature objects like layer-7251 and layer-7252 (linz.staging.kx.gd) fails to load its features on ArcPRO, as it tries to POST to the `/query` endpoint in hopes to fetch the geometries. 

It seems like ArcPRO does a `POST` query instead of a `GET` when there are lots of feature objects. It's basically trying to do the same as a GET query to get the geometries, so enable POST to return the same response.

### How have you solved the problem?
Added a `POSTMapServerQuery` endpoint to function exactly like how it would do with `GET`

### Risks involved
There shouldn't be any.

#### Are there possible or actual performance implications for this change?
It's certainly not a snappy performance since there are lots of features (500000+) when this request is called.

### Deployment/Migration

2024-04-30 02:44 UTC, hamishcampbell approved these changes

2024-05-01 21:11 UTC, rcoup requested changes
Can't we do this with `@RequestMapping(method={GET, POST})` instead of copypasta?

2024-05-02 09:47 UTC, skim618 commented
> Can't we do this with `@RequestMapping(method={GET, POST})` instead of copypasta?

Yes. Simplifies the code alot more as well.
Added a basic POST query test.

2024-05-02 21:14 UTC, rcoup approved these changes
👍

2024-05-07 23:17 UTC, merged